### ISSUE TITLE
List potentially missing some cool host stars

### ISSUE THREAD

**Issue by brackham** [PandoraMission/PandoraTargetList#2]
There are a few cool host stars that I would expect to be in the long list that are missing, such as LP 890-9 (T_eff = 2850 ± 75 K) and LP 791-18 (T_eff = 2960 ± 55 K). It would be good to understand what cut is excluding these targets.

**Comment by benhord** [comment]
This is a good question! Upon deeper investigation, it looks like both of these targets are being cut due to their J magnitudes. Currently, the long list excludes stars with Jmag > 11.5. LP 890-9 and LP 791-18 have Jmag values of 12.258 and 11.559, respectively. This is likely what is occurring for other cool hosts that may be missing from the list.

I believe that these magnitude cuts are not hard and fast rules, but were guidelines meant to encapsulate the most likely range of Pandora's capability. I would imagine that these thresholds would change over time and indeed as the instrument performance is characterized on-sky, so I'm happy to adjust these magnitude cuts, but perhaps this is worth discussing with the larger SWG.
